-- ----------------------------
-- Table structure for CUSTBASEINFO客户基本信息表
-- ----------------------------
DROP TABLE IF EXISTS CUSTBASEINFO;
CREATE TABLE CUSTBASEINFO (
  serverid int4 ,
  custid bigint ,
  fullname varchar(128) ,
  idtype char(1) ,
  singleflag char(1) ,
  idno char(32) ,
  idaddr varchar(64) ,
  sex char(1) ,
  edu char(1) ,
  birthday int4 ,
  native varchar(16) ,
  nation char(1) ,
  addr varchar(128) ,
  postid varchar(16) ,
  faxno varchar(32) ,
  telno varchar(32) ,
  mobileno varchar(32) ,
  email varchar(32) ,
  avocation varchar(32) ,
  contact char(1) ,
  contactfrep char(1) ,
  opendate int4 ,
  closedate int4 ,
  riskfactor varchar(128) ,
  criterion varchar(128) ,
  remark varchar(128) ,
  remark1 varchar(128) ,
  remark2 varchar(128) ,
  idbegindate int4 ,
  idenddate int4 ,
  policeorg varchar(64) ,
  yearchkdate int4 ,
  verifieddate int4 ,
  verifiedflag char(1) ,
  contractverno varchar(32) ,
  ymtid varchar(20) 
)
;
-- ----------------------------
-- Table structure for dictindex数据字典条目定义
-- ----------------------------
DROP TABLE IF EXISTS dictindex;
CREATE TABLE dictindex (
  serverid int4 ,
  dictitem varchar(8),
  itemname char(16),
  itemtype char(1),
  addenable char(1),
  loadlevel int4 ,
  validlen int4 
)
;
-- ----------------------------
-- Table structure for dictlist数据字典表示(营业部,局部)
-- ----------------------------
DROP TABLE IF EXISTS dictlist;
CREATE TABLE dictlist (
  serverid int4 ,
  orgid char(4),
  dictitem varchar(8),
  subitem char(4),
  subitemname varchar(32),
  ctrlflag char(1),
  dispflag char(1)
)
;
-- ----------------------------
-- Table structure for dictvalue数据字典表示(公用,全局)
-- ----------------------------
DROP TABLE IF EXISTS dictvalue;
CREATE TABLE dictvalue (
  serverid int4 ,
  dictitem varchar(8),
  subitem char(4),
  subitemname varchar(32),
  ctrlflag char(1),
  dispflag char(1)
)
;
-- ----------------------------
-- Table structure for eccodesign客户理财计划电子合同约定表
-- ----------------------------
DROP TABLE IF EXISTS eccodesign;
CREATE TABLE eccodesign (
  serverid int4 ,
  custid bigint ,
  fundid bigint ,
  fundcode char(8),
  taacc char(12),
  transacc char(17),
  ectype char(1),
  sno int4 ,
  dbtid varchar(8),
  fullname varchar(120),
  acctype char(1),
  idtype char(1),
  idno char(32),
  orderdate int4 ,
  opertime int4 ,
  operway char(1),
  netaddr char(15),
  operorg char(4),
  remark varchar(32),
  ecsno varchar(32),
  operid int4 ,
  orgid char(4),
  dealflag char(1),
  status char(1),
  reorderdate int4 ,
  reopertime int4 ,
  expand1 varchar(64),
  expand2 varchar(64),
  expand3 varchar(64),
  expand4 varchar(64),
  riskmatch char(1),
  risklevel char(1),
  telno varchar(32),
  mobil varchar(32),
  email varchar(32),
  postid varchar(16),
  addr varchar(120),
  assignflag char(1),
  redeemcontract char(1),
  reservfund numeric(19,2) ,
  dyreservfund numeric(19,2) ,
  resfundexpdate int4 ,
  multisettstatus char(1),
  multisettexp int4 ,
  multisettupdate int4 ,
  lastconvertvol numeric(19,2) ,
  lastdivate int4 ,
  isnewsign char(1),
  beforconvertvol numeric(19,2) ,
  updatedate int4 ,
  specialctrl varchar(32),
  prereservfund numeric(19,2) ,
  prereservfunddate int4 
)
;
-- ----------------------------
-- Table structure for etf_cashcomponent ETF资金信息
-- ----------------------------
DROP TABLE IF EXISTS etf_cashcomponent;
CREATE TABLE etf_cashcomponent (
  date int4  ,
  fundid bigint  ,
  custid bigint  ,
  custname char(16) ,
  orgname varchar(50) ,
  stkcode char(12) ,
  ykkje decimal(18,2)  ,
  djje decimal(18,2)  ,
  ydbzje decimal(18,2)  ,
  kyye decimal(18,2)  ,
  qsje decimal(18,2)  ,
  yled decimal(18,2) 
)
;
-- ----------------------------
-- Table structure for etf_cashcomponent_bf ETF资金信息_备份
-- ----------------------------
DROP TABLE IF EXISTS etf_cashcomponent_bf;
CREATE TABLE etf_cashcomponent_bf (
  date int4 ,
  fundid bigint ,
  custid bigint ,
  custname char(16),
  orgname varchar(50),
  ykkje decimal(18,2) ,
  djje decimal(18,2) ,
  ydbzje decimal(18,2) ,
  kyye decimal(18,2) ,
  qsje decimal(18,2) ,
  yled decimal(18,2) ,
  jzrq int4 
)
;
-- ----------------------------
-- Table structure for etfbaseinfo ETF基本信息表
-- ----------------------------
DROP TABLE IF EXISTS etfbaseinfo;
CREATE TABLE etfbaseinfo (
  serverid int4 ,
  market char(1),
  ofcode char(8),
  ofname varchar(16),
  etftype char(1),
  etfprop char(1),
  etfcode0 char(8),
  etfcode1 char(8),
  etfcode2 char(8),
  tradeunit int4 ,
  ecashcomponet numeric(19,2) ,
  maxcashratio numeric(12,8) ,
  publish char(1),
  tradestate char(1),
  recordnum int4 ,
  totalrecordnum int4 ,
  creationlimit bigint ,
  redemptionlimit bigint ,
  creationlimituser bigint ,
  redemptionlimituser bigint ,
  netcreationlimit bigint ,
  netredemptionlimit bigint ,
  netcreationlimitperuser bigint ,
  netredemptionlimitperuser bigint ,
  tradingday int4 ,
  pretradingday int4 ,
  cashcomponent numeric(19,2) ,
  preecashcomponet numeric(19,2) ,
  navpercu numeric(19,2) ,
  nav numeric(7,4) ,
  rtgsflag char(1),
  I_By int4 ,
  C_By varchar(8),
  remark varchar(32)
)
;
-- ----------------------------
-- Table structure for FUNDASSET 客户货币资产表
-- ----------------------------
DROP TABLE IF EXISTS FUNDASSET;
CREATE TABLE FUNDASSET (
  serverid int4 ,
  orgid char(4),
  fundseq int4 ,
  fundid bigint ,
  moneytype char(1),
  custid bigint ,
  fundlastbal numeric(19,2) ,
  fundbal numeric(19,2) ,
  fundavl numeric(19,2) ,
  overdraw numeric(19,2) ,
  fundbuy numeric(19,2) ,
  fundsale numeric(19,2) ,
  funduncomebuy numeric(19,2) ,
  funduncomesale numeric(19,2) ,
  fundfrz numeric(19,2) ,
  fundunfrz numeric(19,2) ,
  fundtrdfrz numeric(19,2) ,
  fundtrdunfrz numeric(19,2) ,
  fundnightfrz numeric(19,2) ,
  fundloan numeric(19,2) ,
  creditbal numeric(19,2) ,
  creditbuysale numeric(19,2) ,
  fundflag char(1),
  marketvalue numeric(19,2) ,
  fundstandby numeric(19,2) ,
  fundbuysale numeric(19,2) ,
  fundbrkbuy numeric(19,2) ,
  fundrealbuy numeric(19,2) ,
  fundbalprefrz numeric(19,2) ,
  fundcashpro numeric(19,2) ,
  fundavlprefrz numeric(19,2) 
)
;
-- ----------------------------
-- Table structure for FUNDDEBTS 资产负债
-- ----------------------------

DROP TABLE IF EXISTS FUNDDEBTS;
CREATE TABLE FUNDDEBTS (
  serverid int4 ,
  orgid char(4) ,
  custid bigint ,
  fundid bigint ,
  market char(1) ,
  secuid char(10) ,
  moneytype char(1) ,
  debtsid char(1) ,
  unpayamt numeric(19,2) ,
  sumpaidamt numeric(19,2) ,
  sumdebtamt numeric(19,2) ,
  upddate int4 ,
  remark varchar(128) ,
  frzamt numeric(19,2) 
)
;
-- ----------------------------
-- Table structure for FUNDINFO 客户资金账户
-- ----------------------------
DROP TABLE IF EXISTS FUNDINFO;
CREATE TABLE FUNDINFO (
  serverid int4 ,
  custid bigint ,
  orgid char(4) ,
  brhid char(4) ,
  fundid bigint ,
  spellid varchar(8) ,
  fundname varchar(16) ,
  idtype char(1) ,
  idno char(32) ,
  operway varchar(128) ,
  fundkind char(1) ,
  fundlevel char(1) ,
  fundgroup char(1) ,
  funduser0 int4 ,
  funduser1 int4 ,
  brokerid bigint ,
  custmgrid bigint ,
  fundagentright varchar(128) ,
  fundright varchar(512) ,
  fundlimit varchar(128) ,
  fundtrdrule char(1) ,
  trdright varchar(128) ,
  fundrule char(1) ,
  bankcode char(4) ,
  bankbranch char(6) ,
  banknetplace char(8) ,
  pwdctrldays int4 ,
  pwdtype char(1) ,
  fundpwd varchar(32) ,
  linkflag int4 ,
  fundtrdflag char(1) ,
  opendate int4 ,
  closedate int4 ,
  printdate int4 ,
  fundprintdate int4 ,
  status char(1) ,
  policyid char(1) ,
  policykind varchar(12) ,
  cobusiflag char(1) ,
  reportkind varchar(128) ,
  sepecialfee char(1) ,
  specialkind varchar(32) ,
  sfbankcode char(4) ,
  sfopenmoney varchar(8) ,
  fundtype char(1) ,
  activeflag char(1) ,
  iceway varchar(128) ,
  billproway varchar(128) ,
  creditflag char(1) ,
  creditfund char(1) ,
  creditstatus char(1) ,
  lastcreditstatus char(1) 
)
;
-- ----------------------------
-- Table structure for h_orderrec 历史委托表视图
-- ----------------------------
DROP TABLE IF EXISTS h_orderrec;
CREATE TABLE h_orderrec (
  serverid int4 ,
  ordersno int4 ,
  ordergroup int4 ,
  orderid char(10),
  orderdate int4 ,
  operdate int4 ,
  opertime int4 ,
  custid bigint ,
  custkind char(1),
  custgroup char(1),
  custname char(16),
  orgid char(4),
  brhid char(4),
  fundid bigint ,
  moneytype char(1),
  fundkind char(1),
  fundlevel char(1),
  fundgroup char(1),
  secuid char(10),
  rptsecuid char(10),
  market char(1),
  seat char(6),
  stkcode char(8),
  stkname char(8),
  stktype char(1),
  orderprice numeric(9,3) ,
  bondintr numeric(12,8) ,
  orderqty int4 ,
  reportqty int4 ,
  fundavl numeric(19,2) ,
  matchqty int4 ,
  cancelqty int4 ,
  tradefee numeric(12,2) ,
  orderfrzamt numeric(19,2) ,
  clearamt numeric(19,2) ,
  matchamt numeric(19,2) ,
  ordertype char(1),
  nightflag char(1),
  bsflag char(2),
  inputbs char(1),
  cancelflag char(1),
  combtype char(1),
  reporttime int4 ,
  orderstatus char(1),
  recnum int4 ,
  stkdiff int4 ,
  sourcetype char(1),
  bankcode char(4),
  bankid varchar(32),
  bankorderid varchar(32),
  bankfrzsno varchar(64),
  extdbfsno int4 ,
  bankbranch char(6),
  banknetplace char(8),
  brokerid bigint ,
  custmgrid bigint ,
  funduser0 bigint ,
  funduser1 int4 ,
  channel varchar(8),
  agentid bigint ,
  operid int4 ,
  operlevel char(1),
  operorg char(4),
  netaddr char(15),
  operway char(1),
  reportkind varchar(128),
  remark varchar(32),
  creditid char(1),
  creditflag char(1),
  remark1 varchar(255),
  creditfrzqty bigint ,
  creditfrzamt numeric(19,2) ,
  fundmarginfrz numeric(19,2) ,
  funddebtsfrz numeric(19,2) ,
  orderqty2 int4 ,
  orderprice2 numeric(9,3) ,
  confernum int4 ,
  termtype char(1),
  gh_term int4 ,
  linkman char(12),
  linkway varchar(30),
  remaintext varchar(100),
  jysorderid char(10),
  secuid_src char(10),
  discratio numeric(12,8) ,
  seat_src char(6),
  rptseat char(6),
  matchcode varchar(20),
  promisno varchar(8),
  limitstkorder char(1),
  dzsaletype char(1)
)
;
-- ----------------------------
-- Table structure for prezqzhf
-- ----------------------------
DROP TABLE IF EXISTS prezqzhf;
CREATE TABLE prezqzhf (
  serverid int4 ,
  operdate int4 ,
  cleardate int4 ,
  bizdate int4 ,
  sno int4 ,
  relativesno int4 ,
  custid bigint ,
  custname char(16),
  fundid bigint ,
  moneytype char(1),
  orgid char(4),
  brhid char(4),
  custkind char(1),
  custgroup char(1),
  fundkind char(1),
  fundlevel char(1),
  fundgroup char(1),
  digestid int4 ,
  fundeffect numeric(19,2) ,
  fundbal numeric(19,2) ,
  secuid varchar(32),
  market char(1),
  biztype char(1),
  stkcode varchar(16),
  stktype char(1),
  bankcode char(4),
  trdbankcode char(4),
  bankbranch char(6),
  banknetplace char(8),
  stkname char(16),
  stkeffect bigint ,
  stkbal bigint ,
  orderid char(10),
  trdid char(1),
  orderqty bigint ,
  orderprice numeric(9,3) ,
  bondintr numeric(12,8) ,
  orderdate int4 ,
  ordertime int4 ,
  matchqty bigint ,
  matchamt numeric(19,2) ,
  seat char(6),
  matchtimes int4 ,
  matchprice numeric(9,3) ,
  matchtime int4 ,
  matchcode varchar(20),
  fee_jsxf numeric(12,2) ,
  fee_sxf numeric(12,2) ,
  fee_yhs numeric(12,2) ,
  fee_ghf numeric(12,2) ,
  fee_qsf numeric(12,2) ,
  fee_jygf numeric(12,2) ,
  fee_jsf numeric(12,2) ,
  fee_zgf numeric(12,2) ,
  fee_qtf numeric(12,2) ,
  bsflag char(2),
  feefront numeric(12,2) ,
  sourcetype char(1),
  bankid varchar(32),
  agentid bigint ,
  operid int4 ,
  operway char(1),
  operorg char(4),
  operlevel char(1),
  netaddr char(15),
  chkoper int4 ,
  checkflag char(1),
  brokerid bigint ,
  custmgrid bigint ,
  funduser0 bigint ,
  funduser1 int4 ,
  privilege numeric(19,2) ,
  remark varchar(32),
  ordersno int4 ,
  pathid varchar(16),
  cancelflag char(1),
  reportkind varchar(128),
  creditid char(1),
  creditflag char(1),
  prodcode char(12),
  settrate numeric(12,8) 
)
;
-- ----------------------------
-- Table structure for secuid 股东帐号
-- ----------------------------
DROP TABLE IF EXISTS secuid;
CREATE TABLE secuid (
  serverid int4 ,
  custid bigint ,
  market char(1),
  secuid char(10),
  rptsecuid char(10),
  insidesecuid char(10),
  orgid char(4),
  name char(16),
  idtype char(1),
  idno char(32),
  regflag char(1),
  bondreg char(1),
  seat char(6),
  channel varchar(8),
  secucls char(1),
  foreignflag char(1),
  seculevel char(1),
  secuseq int4 ,
  securight varchar(512),
  seculimit varchar(128),
  status char(1),
  creditflag char(1),
  opendate int4 ,
  closedate int4 ,
  secuseat char(6),
  extprop varchar(128),
  limitflag char(1),
  specialflag char(1),
  swapflag char(1)
)
;
-- ----------------------------
-- Table structure for specialcommission 账户特殊收费
-- ----------------------------
DROP TABLE IF EXISTS specialcommission;
CREATE TABLE specialcommission (
  serverid int4 ,
  orgid char(4),
  fundid bigint ,
  custid bigint ,
  market char(2),
  stktype char(2),
  trdid char(2),
  moneytype char(2),
  bsflag char(2),
  minfee numeric(19,2) ,
  maxfee numeric(19,2) ,
  commissionrate numeric(12,8) ,
  pt_operway varchar(128),
  feemode char(2),
  crt_time varchar(50)
)
;
-- ----------------------------
-- Table structure for uncommitclear 未交收表
-- ----------------------------
DROP TABLE IF EXISTS uncommitclear;
CREATE TABLE uncommitclear (
  serverid int4 ,
  sno int4 ,
  market char(1),
  orderdate int4 ,
  matchdate int4 ,
  rptbsflag char(4),
  orderid char(10),
  matchcode varchar(20) ,
  moneytype char(1),
  bpsecuid varchar(32),
  stkcode varchar(12),
  linkstk varchar(12),
  stkname char(16),
  stktype char(1),
  trdid char(1),
  settlefundays int4 ,
  settlestkdays int4 ,
  funduseflag char(1),
  stkusedflag char(1),
  biztype char(1),
  busitype char(4),
  matchtime int4 ,
  matchqty bigint ,
  matchprice numeric(9,3) ,
  bondintr numeric(12,8) ,
  matchamt numeric(19,2) ,
  mateno varchar(32),
  seat char(6),
  pathid varchar(16),
  dbfrec int4 ,
  secuid varchar(32),
  custname char(16),
  fundid bigint ,
  fundkind char(1),
  fundlevel char(1),
  fundgroup char(1),
  orgid char(4),
  brhid char(4),
  custid bigint ,
  agentid bigint ,
  custkind char(1),
  custgroup char(1),
  orderqty bigint ,
  orderprice numeric(9,3) ,
  ordertime int4 ,
  bsflag varchar(2),
  operway char(1),
  operid int4 ,
  operlevel char(1),
  operorg char(4),
  netaddr char(15),
  sourcetype char(1),
  bankcode char(4),
  bankorderid char(10),
  bankid varchar(32),
  status char(1),
  remark varchar(32),
  clearedamt numeric(19,2) ,
  fee_jsxf numeric(12,2) ,
  fee_sxf numeric(12,2) ,
  fee_yhs numeric(12,2) ,
  fee_ghf numeric(12,2) ,
  fee_qsf numeric(12,2) ,
  fee_jygf numeric(12,2) ,
  fee_jsf numeric(12,2) ,
  fee_zgf numeric(12,2) ,
  fee_qtf numeric(12,2) ,
  feefront numeric(12,2) ,
  privilege numeric(19,2) ,
  bb_matchdate int4 ,
  bb_matchclearamt numeric(19,2) ,
  matchtimes int4 ,
  ordersno int4 ,
  bankbranch char(6),
  banknetplace char(8),
  brokerid bigint ,
  custmgrid bigint ,
  funduser0 bigint ,
  funduser1 int4 ,
  reportkind varchar(128),
  creditid char(1),
  creditflag char(1),
  fee_one_yhs numeric(12,2) ,
  fee_one_ghf numeric(12,2) ,
  fee_one_qsf numeric(12,2) ,
  fee_one_jygf numeric(12,2) ,
  fee_one_jsf numeric(12,2) ,
  fee_one_zgf numeric(12,2) ,
  fee_one_qtf numeric(12,2) ,
  fee_one_fxj numeric(12,2) ,
  prodcode varchar(12),
  discratio numeric(12,8) ,
  bizprop int4 
)
;


